### ISSUE TITLE
GetYahooStockCode method do not return expected value 

### ISSUE THREAD

**Issue by marcoplaut** [ZacMarcus/YahooFinance.NET#1]
Hello,

The following method do not return correct values except for US, UK & australian market (ok, the most important ones ;) )
```
public string GetYahooStockCode(string exchange, string code)
		{
			switch (exchange)
			{
				case "ASX":
					return $"{code}.AX";
				default:
					return code;
			}
		}
```

The complete list of suffix is available on http://finance.yahoo.com/exchanges

Maybe an enum of MarketExchange can make the use of the API easier ?

**Comment by ZacMarcus** [comment]
Thats great! I couldn't find a list of Yahoo suffixes when I first wrote it.

Are you able to get a list of exchange abbreviations so we have something to map the suffixes to?

**Comment by ZacMarcus** [comment]
I refactored the GetYahooStockCode method to make it easier to add exchanges/suffixes.

You can add them in the _exchanges dictionary in YahooExchangeHelper.cs.

**Comment by ZacMarcus** [comment]
I have added all the exchanges from http://www.wikinvest.com/wiki/List_of_Stock_Exchanges

That doesn't cover everything in the list from http://finance.yahoo.com/exchanges but I can't find the others.

Feel free to add a pull request if you find them.

**Comment by marcoplaut** [comment]
That was fast ! 
Thanks a lot : i'll test that in coming days :)
