### ISSUE TITLE
GetName possibility?

### ISSUE THREAD

**Issue by halgurdh** [ZacMarcus/YahooFinance.NET#10]
Would it be possible to get the name of the historicprice??

Im trying to get it 2 or 3 symbols in one .csv file

**Comment by ZacMarcus** [comment]
I didn't see any way to get the name from the Yahoo Finance API. If you know of a way, please let me know or submit a pull request.

If you need multiple symbols in one CSV, why can't you store the symbol name (eg. 'AFI') in each row of the CSV file?
