### ISSUE TITLE
Yahoo Url has been changed

### ISSUE THREAD

**Issue by bobby68** [ZacMarcus/YahooFinance.NET#13]
Yahoo changed url couple of days ago, so connection with a server cannot be established. New url starts with https://query1.finance.yahoo.com/v7/finance/download...

**Comment by unimatrix27** [comment]
@bobby68  have you verified this URL? I am just getting a 404.

**Comment by unimatrix27** [comment]
ok as it seems this only works with cookie authorization now so its personalized. 
Look here: https://github.com/IvanTrendafilov/YahooFinanceAPITokens

i guess the lib would need a confic option or something to set the personal token.

**Comment by unimatrix27** [comment]
I have implemented a change where the API uses the new token and cookie approach, however now i can only unit test them if I hardcode my personal token in there. 

I will put this to my fork with the tokens removed so maybe someone wants to look at the code and has an idea how to do that. 
https://github.com/unimatrix27/YahooFinance.NET/commit/da1cf97c5ebbea9edc9c7561c487e85a9ce726e0

**Comment by bobby68** [comment]
unimatrix27, thanks for working on this. I didn't put a complete URL there, just the fixed part. For one year of AAPL data, my browser shows https://query1.finance.yahoo.com/v7/finance/download/AAPL?period1=1463832130&period2=1495368130&interval=1d&events=history&crumb=9w3.dCKfQnz
Unfortunately, it seems as if Yahoo Finance is winding down. In last couple of days, even for the manual downloads, I got quite a few CSV files with corrupted data (several lines with date followed by nulls for other data fields)- never happened to me before..

**Comment by ZacMarcus** [comment]
Thanks for your help. I have made the changes to fix this.
