### ISSUE TITLE
i think yahoo service has changed i'can't  get historial quotes

### ISSUE THREAD

**Issue by ManelBF** [ZacMarcus/YahooFinance.NET#15]
try various times other cookies and crumbs...  and don't work.
it worked for me fine until 10 days ago.
it's and excelent API,thank's Zac.
can be yahoo has changed anything?

thank's

**Comment by ManelBF** [comment]
the lenght of B coockie has increase a lot.

NOW Cockie B: "1qeq01lcagd88&b=4&d=qFYcCHtpYFJFC5E_lUuwgF46yb4-&s=oo&i=Wg10anAp1SZtCwo1_LRD"

BEFORE = "1qeq01lcagd88&b=3&s=e9"

**Comment by ZacMarcus** [comment]
I just tested it with a new cookie/crumb and the cookie is the usual length for me, just like you 'before'. I put it into my unit tests and everything ran successfully. 

How are you getting the cookie? Are you getting the cookie with chrome?

**Comment by ManelBF** [comment]
Thanks for the answer Zac,
with Chrome the problem persists:
Nom
B
Contingut
**1qeq01lcagd88&b=4&d=qFYcCHtpYFJFC5E_lUuwgF46yb4-&s=oo&i=Wg10anAp1SZtCwo1_LRD**
Domini
.yahoo.com
Camí
/
Envia per a
Qualsevol tipus de connexió
Accessible a l'script
Sí
Creada
dimecres, 6 de setembre de 2017 a les 11:11:37
Data de caducitat
dijous, 6 de setembre de 2018 a les 11:11:37

## i try to get the cookie B with Internet Explorer (inspect element), and it works!

   URL de la solicitud: https://finance.yahoo.com/quote/AFI.AX/history?p=AFI.AX
   Método de la solicitud: GET
   Código de estado: 200 / 
 - Encabezados de solicitud
   Accept: text/html, application/xhtml+xml, image/jxr, */*
   Accept-Encoding: gzip, deflate
   Accept-Language: es-ES
   ## Cookie: B=aaa5tqdcqvfc5&b=3&s=oc;
 PRF=t%3DAFI.AX
   Host: finance.yahoo.com
   User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko/20100101 Firefox/12.0
 - Encabezados de respuesta
   age: 3
   content-type: text/html; charset=utf-8
   date: Wed, 06 Sep 2017 09:21:59 GMT
   public-key-pins-report-only: max-age=2592000; pin-sha256="2oALgLKofTmeZvoZ1y/fSZg7R9jPMix8eVA6DH4o/q8="; pin-sha256="cAajgxHlj7GTSEIzIYIQxmEloOSoJq7VOaxWHfv72QM="; pin-sha256="SVqWumuteCQHvVIaALrOZXuzVVVeS7f4FGxxu6V+es4="; pin-sha256="UZJDjsNp1+4M5x9cbbdflB779y5YRBcV6Z6rBMLIrO4="; pin-sha256="JbQbUG5JMJUoI6brnx0x3vZF6jilxsapbXGVfjhN8Fg="; pin-sha256="lnsM2T/O9/J84sJFdnrpsFp3awZJ+ZZbYpCWhGloaHI="; pin-sha256="h6801m+z8v3zbgkRHpq6L29Esgfzhj89C1SyUCOQmqU="; pin-sha256="SQVGZiOrQXi+kqxcvWWE96HhfydlLVqFr4lQTqI5qqo="; pin-sha256="q5hJUnat8eyv8o81xTBIeB5cFxjaucjmelBPT2pRMo8="; pin-sha256="vPtEqrmtAhAVcGtBIep2HIHJ6IlnWQ9vlK50TciLePs="; pin-sha256="lpkiXF3lLlbN0y3y6W0c/qWqPKC7Us2JM8I7XCdEOCA="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="2fRAUXyxl4A1/XHrKNBmc8bTkzA7y4FB/GLJuNAzCqY="; pin-sha256="dolnbtzEBnELx/9lOEQ22e6OZO/QNb6VSSX2XHA3E7A="; report-uri="http://csp.yahoo.com/beacon/csp?src=yahoocom-hpkp-report-only"
   server: ATS

**thanks again ZAC!**

**Comment by ManelBF** [comment]
i try the same with Edge and the result is like Chrome:

   Cookie: PRF=t%3DAFI.AX;
 ## B=4sqbpclcaghnn&b=4&d=qFYcCHtpYFJFC5E_lUuwgF46yb4-&s=qo&i=z4ZIIpvmcfe6iH07ZBRp;


 T=z=pVTZZBpp6dZBkQlv4wX8U4oNDA3MwY2TjYzNzVOTk8zMTdOND&a=QAE&sk=DAA9jtitwPpFxY&ks=EAAQRYgh90a37SNe6hmnWEIxA--~G&kt=EAARl4q9JC32VJZjDFsxphZtQ--~I&ku=FAAKqurVUTU7glwBncqGwPCTHL1jjUuuvGbuR8jLesRAeb2Zz1YI.AnArU1N6CP5sU1PGisxeiLBq2abeekbrVlQFQVpJWo7SvnqDGnFVI.llJ96p3.z_vcVZOeEYKT5kjJQt.Pqd1LoM3VVzDxEyeFSkLPwZoOj5iuEtK0LfXvIWc-~A&d=ZwEzT01PR0lOSUhIV0xXSUxITzVWTUpVUVJWUQFzbAFNemN3TkFFeE9URTBNREk1T1RnME5qQTVNekUxTkEtLQFhAVFBRQFhYwFBT3pSa2ZFZQFhbAFib3NjaC5tYW5lbAFzYwFkZXNrdG9wX3dlYgFmcwFhMVFUZUs5WlpUVnABenoBcFZUWlpCQTdF&af=JnRzPTE0OTk4MDUwMzMmcHM9bGFFOVF0ZFhRd2xOcDRsRVVzSVNQUS0t; F=d=TCa2eNs9vNreDzZ_mp08sFVMQF5QTL5c6af5Z_PMlA--; PH=fn=IA_UGiMeX8K0yswQxmI-&l=en-US&i=us; Y=v=1&n=0lcdtihp58erk&l=up0dcia17luxcvk81149416hc8meheb5sw9tg20l/o&p=f1svves00000000&r=129&lg=en-US&intl=us; SSL=v=1&s=WjJFBiTjUsH_m0QG_94nuDYJEcPw_brW5.3RJsRCDFYmvtN4IbDwzN_Tr9ZZc4qId7FA5GClRRe.06Kb6xqCaQ--&kv=0&ku=biqRQZ4urYp6TmbtNMjyZPIs2x4uTmuK7W5N6bYdtp9rV.G.bC6Fe0Gn6FN9NGPA1c2zQPuc.arQR04CIzC_aatxWUIfwUmKaYmkQu6gpe.LF2RN.WSIAFw0FfHRyovxfTYWWBpSQGSfPTBlCHp8iPIDNY_M.ZOKlO5Qoh8KEcc-~A; AO=u=1

**Comment by ZacMarcus** [comment]
When I tried the other day, I was using chrome on Windows 10. I think there
are usually a couple yahoo cookies. Are you sure you got the right one?

Is Windows in English for you? Maybe it had to do with the language
settings?

**Comment by ManelBF** [comment]
my be, by now, with the iexplorer coockie it works!
if in the future it fails, i'm going to investigate again.

the fact is that different configurations or explorers (lang, OS, etc) changes the B coockie

**Comment by ZacMarcus** [comment]
Thanks for looking into it. I'm going to close this issue for now since you got it working again.
