### ISSUE TITLE
Could not install package 'YahooFinance.NET 4.0.0'

### ISSUE THREAD

**Issue by moiseyo** [ZacMarcus/YahooFinance.NET#16]
Install-Package : Could not install package 'YahooFinance.NET 4.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

My Computer  W10 Prof, VS 2013 Prof 

Any ideas

**Comment by ZacMarcus** [comment]
This project is built using .NET 4.6.1 so you will need to target .NET 4.6.1 or higher in your project.

**Comment by moiseyo** [comment]
Hi I install Vs 2017  and now i can getting error  999 and  403


The view only changes for the lead dog.

**Comment by ZacMarcus** [comment]
What .NET version are you using in your project?

What are the error messages? I can't see anything for error 999.

Error 403 is a authentication issue. Are you able to install any other packages?

"The view only changes for the lead dog." - I have no idea what this means.
