### ISSUE TITLE
YahooFinance.GetRealTimeData & YahooFinance.GetHistoricalDividendData is not working

### ISSUE THREAD

**Issue by davy889** [ZacMarcus/YahooFinance.NET#19]
Hi ZacMarcus,

I have tried  YahooFinance API,  YahooFinance.GetDailyHistoricalPriceData is working to get the historical data. 

However, when I call the YahooFinance.GetRealTimeData(yahoostockcode), there is  WebException: The remote name could not be resolved: 'download.finance.yahoo.com'

I also tried Dim listdividendhistory As Object = YahooFinance.GetHistoricalDividendData(yahoostockcode), but no record count returns . 

Here is my coding, do I need to handle the cookie and crumb ?

        Dim cookie As String = "YOUR_COOKIE"
        Dim crumb As String = "YOUR_CRUMB"

        Dim exchange As String = "HKG"
        Dim symbol As String = "0001"

        Dim YahooFinance As New YahooFinance.NET.YahooFinanceClient(cookie, crumb)  'retrieve cookies
        Dim yahoostockcode = YahooFinance.GetYahooStockCode(exchange, symbol)

Dim listhistoricalprice As Object = YahooFinance.GetDailyHistoricalPriceData(yahoostockcode)
        Console.WriteLine("Historical Price")
        For Each histprice In listhistoricalprice
            With histprice
                Console.WriteLine("Date: " & .Date & " Open: " & .Open & " High: " & .High & " Low: " & .Low & " Close: " & .Close & " AdjClose: " & .AdjClose & " Volume: " & .Volume)
            End With
        Next

        Dim listrealtimeprice As Object = YahooFinance.GetRealTimeData(yahoostockcode)
        Console.WriteLine("Real Time Price")
        For Each realtimeprice In listrealtimeprice

            With realtimeprice
                Console.WriteLine("Ask: " & .Ask & " Bid: " & .Bid & " Last: " & .Last & " PreviousClose: " & .PreviousClose _
                    & " Open: " & .Open & " High: " & .High & " Low: " & .Low & " LastTradeTime: " & .LastTradeTime & " Volume: " & .Volume _
                    & "Symbol: " & .Symbol & " Name: " & .Name)

            End With
        Next

Thanks
Davy

**Comment by ZacMarcus** [comment]
Last time I looked (3 years ago) you needed a cookie and crumb to be able to perform the query. The ReadMe has a way to get the cookie / crumb. The api may have changed as well. You should be able to get the query string and run it in your browser and see if you get a response.
