### ISSUE TITLE
Parsing is bound to culture of current thread

### ISSUE THREAD

**Issue by zacko83** [ZacMarcus/YahooFinance.NET#3]
Hi ZacMarcus,

I noticed the values returned from this package are far too big (usually x10000 of the correct value).

The reason for this is quite simple: Yahoo, of course, delivers its values in US format. My default thread culture however is German. I took a look in the source code and noticed you're using the default parse methods like `decimal.Parse(values[1])` without specifying the culture explicitly. 

So the problem would be solved by specifying the US format explicitly to the parse methods.

Thanks a lot,
Zacko

**Comment by ZacMarcus** [comment]
I have updated the package.
